FROM python:3.11-slim

WORKDIR /app

# نسخ ملف المتطلبات وتثبيت المكتبات
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# نسخ مجلد Backend
COPY backend/ /app/

# إنشاء مجلد البيانات
ENV PORT=5000
ENV DATA_DIR=/app/data
RUN mkdir -p /app/data

# فتح المنفذ
EXPOSE 5000

# تشغيل التطبيق
CMD ["python", "app.py"]
